Repository AbhiPatel10/AISKCON-CONSTRUCTION, pull requests merged in 2023-06, with the labels that each got.

#265 add custom chatbot
  css/style.css
  index.html
  js/main.js
Labels: gssoc23, Level 3

#288 Hover Effect Added
  ServiceSection/index.html
  aboutUs/index.html
  contact/index.html
  css/style.css
  index.html
  repair/index.html
  repair/style.css
Labels: gssoc23, level2

#293 Safety part added
  aboutUs/index.html
  aboutUs/style.css
  img/vectors/safety (1).png
Labels: gssoc23, level2

#294 Buttons in the repair section fixed
  repair/style.css
Labels: bug, gssoc23, level1

#344 Formatted the about page - Safety section
  aboutUs/index.html
  aboutUs/style.css
Labels: enhancement, gssoc23, level1

#346 Added a heading to the About Us hero section.
  aboutUs/index.html
  aboutUs/style.css
Labels: enhancement, gssoc23, level1, Under Review

#355 Fixed the improper formatting in the footer of the About Us page
  aboutUs/index.html
  aboutUs/style.css
  contribution.md
Labels: gssoc23

#382 New branch
  contribution.md
  img/bg/repair2.webp
  repair/style.css
Labels: gssoc23, level1

#373 [Fixes #352] Fixed Navbar Scroll Problem
  css/style.css
Labels: gssoc23, level1

#390 Improved UI of scrollbar
  css/style.css
Labels: gssoc23, level1

#391 Added Contribution File
  aboutUs/style.css
  contribution.md
Labels: gssoc23, level1

#388 added new background image of service page
  ServiceSection/index.html
  ServiceSection/style.css
  img/bg/servicenew.jpg
Labels: gssoc23, level1

#438 Added Favicon to Secondary Pages
  ServiceSection/index.html
  aboutUs/index.html
  contact/index.html
Labels: enhancement, gssoc23, level1

#446 Enhanced UI on mobile #441
  css/style.css
Labels: enhancement, level2

#428 Adding Links and hover effect to "Services", "Repairs" and "Contact" headings in the footer section
  ServiceSection/index.html
  aboutUs/index.html
  aboutUs/style.css
  contact/index.html
  css/style.css
  repair/index.html
Labels: enhancement, gssoc23, level1, Under Review

#435 modified service section
  ServiceSection/style.css
Labels: enhancement, good first issue, gssoc23, level1
